version: "3"

services:
  db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: pycarbonara
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
    networks:
      - server

  web:
    build: .
    image: bylearn/pycarbonara:latest
    command: "dockerize -wait tcp://db:5432 -wait-retry-interval 10s entry-application"
    restart: always
    volumes:
      - .:/code
    ports:
      - "8080:8000"
    depends_on:
      - db
    networks:
      - server

networks:
  server:
    driver: bridge
