version: "3"

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: pycarbonara
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
    volumes:
      - master_db_data:/var/lib/postgresql/data
    networks:
      - server

  web:
    build: .
    image: bylearn/pycarbonara:latest
    command: "dockerize -wait tcp://db:5432 -wait-retry-interval 10s entry-application"
    restart: always
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - server

volumes:
  master_db_data:
    driver: local

networks:
  server:
    driver: bridge
