name: pycarbonara
region: nyc
services:
  - dockerfile_path: Dockerfile
    github:
      branch: master
      deploy_on_push: true
      repo: bylearn/pycarbonara
    http_port: 8000
    instance_count: 1
    instance_size_slug: basic-xxs
    name: pycarbonara
    run_command: entry-application
    routes:
      - path: /
    envs:
      - key: ENVIRONMENT
        value: production
        scope: RUN_TIME
        type: GENERAL
      - key: PORT
        value: 8000
        scope: RUN_TIME
        type: GENERAL
