databases:
  - engine: PG
    name: db
    num_nodes: 1
    size: db-s-dev-database
    version: "12"
name: pycarbonara
region: nyc
services:
  - dockerfile_path: Dockerfile
    envs:
      - key: ENVIRONMENT
        scope: RUN_AND_BUILD_TIME
        value: production
      - key: PORT
        scope: RUN_AND_BUILD_TIME
        value: "8000"
      - key: DATABASE_URL
        scope: RUN_TIME
        value: ${db.DATABASE_URL}
    github:
      branch: master
      deploy_on_push: true
      repo: bylearn/pycarbonara
    http_port: 80
    instance_count: 1
    instance_size_slug: basic-xxs
    name: pycarbonara
    routes:
      - path: /
    run_command: entry-application
